language: node_js # 언어는 node_js
node_js:
  - "12.8.0" # node_js에 버전 10.14
before_install: # 패키지를 다운로드 받기 전
  - npm install -g yarn # yarn을 글로벌로 설치
branches:
  only:
    - main
before_deploy: # 배포하기전 하는 작업들
  - rm -rf node_modules # travis가 설치한 node_moduels를 삭제
  - zip -r travis-ci-test * # travis-ci-test 라는 이름으로 zip 파일 생성
  - mkdir -p deploy # deploy 라는 디렉터리를 만듬
  - mv travis-ci-test.zip deploy/travis-ci-test.zip # deploy 디렉터리로 travis-ci-test.zip 파일을 이동
deploy: # 배포
  - provider: s3 # AWS S3를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: travis-ci-test-s3 # S3에 생성한 버킷
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy # deploy 디렉터리에 있는 파일을 s3로 업로드 하겠다는 의미
    wait-until-deployed: true
    on:
      repo: wkdaudwn11/travice-ci-test #Github 주소
      branch: master
  - provider: codedeploy # AWS CodeDeploy를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: travis-ci-test-s3 # AWS CodeDeploy가 다운로드 받은 버킷
    key: travis-ci-test.zip # 해당 버킷에 저장되어 있는 파일 이름
    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
    application: travis-ci-test # AWS 배포 애플리케이션
    deployment_group: travis-ci-test-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: wkdaudwn11/travis-ci-test
      branch: main
notifications: # 성공 실패 여부 알림
  email:
    recipients:
      - wkdaudwn11@naver.com
