language: node_js # 언어는 node_js
node_js:
  - "12.8.0" # node_js에 버전 10.14
before_install: # 패키지를 다운로드 받기 전
  - npm install -g yarn # yarn을 글로벌로 설치
branches:
  only:
    - deploy
deploy: # 배포
  - provider: codedeploy # AWS CodeDeploy를 의미
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    application: travis-ci-test-code-deploy-service # AWS 배포 애플리케이션
    deployment_group: travis-ci-test-group # AWS 배포 애플리케이션에 만들어져 있는 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: wkdaudwn11/travice-ci-test
      branch: deploy
notifications: # 성공 실패 여부 알림
  email:
    recipients:
      - wkdaudwn11@naver.com
